### ISSUE TITLE
Optimize function breaking when not using additional constraints

### ISSUE THREAD

**Issue by theo1filos** [7purplebulls/financial-opt-tools#4]
Test Case

I want to run simple_mvo without any additional constraints. Since I am not using any constraints there is no need to define a symbols dictionary beacause there are no corresponding constraint symbols needed to be mapped. 

`# refer to model definition for keyword arguments, etc.
mvo_1 = SimpleMVO(assets_1, target_return; short_sale=false)
optimize(mvo_1)`

Error

`LoadError: MethodError:`optimize`has no method matching optimize(::JuPOT.SimpleMVO{Float64,ASCIIString})
Closest candidates are:
  optimize{T}(::JuPOT.AbstractModel, !Matched::Dict{Symbol,T})
  optimize{T}(::JuPOT.AbstractModel, !Matched::Dict{Symbol,T}, !Matched::Any)
while loading In[14], in expression starting on line 9`

**Comment by ShenW123** [comment]
Commit d797e1a567e47e9a995e0bf019635cfa9f3408b3
should have made these optional inputs
